# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B-18-NzwELJ7XFKCtvP3SecLQVOBOMi_
"""

# Personal Introduction Program


name = input("Enter your name: ")
age = input("Enter your age: ")
hobby = input("Enter your hobby: ")


print("\n----------------------------")
print(" Welcome to the Program! ")
print("----------------------------\n")

print(f"Hello {name}! ")
print(f"You are {age} years old.")
print(f"Your hobby is: {hobby} ")
print("\nNice to meet you! Have a great day ")